### PR TITLE
Fix tests and don't offer a specific remote backend

### LINKED ISSUE #45: Rename the project (terraform-packet-openstack)
In order to submit this to the Terraform Registry, we'll need to rename the project to something like terraform-packet-openstack.

https://metal.canny.io/integrations/p/openstack-terraform-module

### LINKED ISSUE #47: Remove testing files from the project
I ran into a few things when trying to `terraform plan` this:
* `main.tf` includes a TF Cloud backend that is specific to the testing environment. This file will prohibit users from consuming the module without modification.
   I think we should move the contents of this file to a secret and create it at test time:
   ```
    - name: Create testing backend config
      run: |
        echo $BACKEND_FILE >> backend.tf
      shell: bash
      env:
        BACKEND_FILE : ${{secrets.BACKEND_FILE}}
     ```
* `OpenStack.tf` could be `main.tf` (since the existing `main.tf` would become `backend.tf`)
* There is a root terraform.yml file which is nearly identical to the one in .github/, the one in the root adds `terraform fmt` and `terraform plan`
* `terraform fmt` applies a few changes to the project that should be included in the PR

### PR DESCRIPTION
**Pull request by displague**
Fixes #45 
Fixes #47 

The `main.tf` file was converted to `backends.hcl` format (https://www.terraform.io/docs/backends/types/remote.html#using-cli-input) and moved into a `BACKEND_FILE` secret in GH Actions

### CODE REVIEW

**Comment by displague** [comment]
@jmarhee What is the `null_resource.controller-openstack` dependencies that `plan` is missing here? Was this renamed or is it perhaps in a file that is not in the repository?  I can't find references to that resource in the old tagged revisions either.

I do see `controller-keystone` in the project.

**Comment by displague** [comment]
We also seem to be missing ExternalNetwork.sh (https://github.com/equinix/terraform-metal-openstack/issues/37).
Is ExternalNetwork.tf necessary?


The `terraform plan` on this PR is not finishing

**Comment by jmarhee** [comment]
The ExternalNetworks.tf was one of the files suffixed with `.off`, so I didn't catch that a resource it named wasn't present. We can remove this, and reimplement later if necessary. 

The resource in NovaConsole should read `controller-nova` rather than `openstack`-- this file was also suffixed .off-- updating that resource name should suffice.

**Comment by displague** [comment]
@jmarhee I've included changes to remove those files.

The plan tests are currently failing because this project is not configured with an EM API token for testing. I thought it might pull this from state using the TF_API token, but that is not the case (perhaps because I renamed the variable, or perhaps because variables are not pulled from backends).

Do you have an existing token we can configure here?

I do think we'll need to address #49 too, but we can address that in a separate issue once we see that the plan and apply is working (which it does from my local testing of this branch).

**Comment by displague** [comment]
If this project can get by with a project token, we could try this: https://github.com/displague/metal-actions-example

It would generate a project id/name/token/ssh key for our testing and destroy it when done.
https://github.com/displague/metal-project-action#output

We could use the same projectName on each build so we don't get excessive build failure devices. Instead we will end up with tests getting stuck until the known projectName is manually deleted. The sweeper could run first (if it is taught how to delete projects by name rather than id alone).

**Comment by displague** [comment]
I've opened another ticket to track the need for adding secrets: https://github.com/equinix/terraform-metal-openstack/issues/50. If you are comfortable with this PR, @jmarhee, maybe we merge this now (it gets TF planning and applying again) and we'll address the test secrets next.

**Comment by jmarhee** [comment]
Looks good. I think we can proceed.

**Pull request merged**
